"""auto

Revision ID: 8a44b25057c3
Revises: 
Create Date: 2026-05-29 03:05:47.616262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a44b25057c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('game_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('patch', sa.String(length=16), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_game_creation'), 'matches', ['game_creation'], unique=False)
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('game_name', sa.String(length=64), nullable=False),
    sa.Column('tag_line', sa.String(length=32), nullable=False),
    sa.Column('profile_icon_id', sa.Integer(), nullable=True),
    sa.Column('summoner_lvl', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_puuid'), 'players', ['puuid'], unique=True)
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('game_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('champion_name', sa.String(length=32), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('team_position', sa.String(length=16), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('creep_score', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puuid', 'match_id')
    )
    op.create_index(op.f('ix_match_participants_game_creation'), 'match_participants', ['game_creation'], unique=False)
    op.create_index(op.f('ix_match_participants_match_id'), 'match_participants', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_participants_puuid'), 'match_participants', ['puuid'], unique=False)
    op.create_table('ranked_entrys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('queue_type', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.String(length=4), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('looses', sa.Integer(), nullable=False),
    sa.Column('league_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puuid', 'queue_type')
    )
    op.create_index(op.f('ix_ranked_entrys_puuid'), 'ranked_entrys', ['puuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranked_entrys_puuid'), table_name='ranked_entrys')
    op.drop_table('ranked_entrys')
    op.drop_index(op.f('ix_match_participants_puuid'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_match_id'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_game_creation'), table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_index(op.f('ix_players_puuid'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_game_creation'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
